---
version: "3"
services:
  mtproto-proxy:
    #image: telegrammessenger/proxy:latest
    build:
      context: .
      args:
        MTPROTO_REPO_URL: ${MTPROXY_REPO_URL}
    container_name: mtproto-proxy
    volumes:
      - ./volumes/config:/data
    restart: unless-stopped
    ports:
      - 2024:2024/udp
      - 2024:2024/tcp
    environment:
      - SECRET
      - WORKERS
      - MTPROTO_REPO_URL
